# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 6111153722c721d1b43bc64cb9a6557a66da3307

{
  "title": "Шкаф IKEA3",
  "description": " Опять"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/18/
Content-Type: application/json
Authorization: Token 6111153722c721d1b43bc64cb9a6557a66da3307

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2&status=OPEN
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2024-02-16
Content-Type: application/json
