# Generated by Django 4.2.7 on 2024-01-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(through='articles.ArticlePosition', to='articles.tag'),
        ),
    ]
