# Generated by Django 4.2.7 on 2024-01-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_teacher_options_remove_student_teachers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
