# Generated by Django 4.2.7 on 2024-01-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_rename_teachers_student_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
